import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://ums.lpu.in/');
  const page1Promise = page.waitForEvent('popup');
  await page.getByText('Get Started').first().click();
  const page1 = await page1Promise;
  await page1.getByRole('textbox', { name: 'User ID' }).click();
  await page1.getByRole('textbox', { name: 'User ID' }).fill('12214922');
  await page1.getByRole('textbox', { name: 'Password' }).click();
  await page1.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page1.getByRole('textbox', { name: 'Password' }).fill('n');
  await page1.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page1.getByRole('textbox', { name: 'Password' }).fill('');
  await page1.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page1.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page1.getByRole('textbox', { name: 'Password' }).fill('NADAUN@0808');
  await page1.locator('#CaptchaCodeTextBox').click();
  await page1.locator('#CaptchaCodeTextBox').press('CapsLock');
  await page1.locator('#CaptchaCodeTextBox').press('CapsLock');
  await page1.locator('#CaptchaCodeTextBox').fill('U');
  await page1.locator('#CaptchaCodeTextBox').press('CapsLock');
  await page1.locator('#CaptchaCodeTextBox').press('CapsLock');
  await page1.locator('#CaptchaCodeTextBox').fill('UksdpC');
  await page1.locator('#CaptchaCodeTextBox').press('Enter');
  // await page1.getByRole('button', { name: 'Login' }).click();
  // await page1.getByRole('button', { name: 'OK' }).click();
  // await page1.getByRole('textbox', { name: 'Password' }).click();
  // await page1.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  // await page1.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  // await page1.getByRole('textbox', { name: 'Password' }).fill('N');
  // await page1.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  // await page1.getByRole('textbox', { name: 'Password' }).fill('Nadaun@0808');
  // await page1.locator('#CaptchaCodeTextBox').click();
  // await page1.locator('#CaptchaCodeTextBox').press('CapsLock');
  // await page1.locator('#CaptchaCodeTextBox').fill('898PM');
  // await page1.locator('#CaptchaCodeTextBox').press('Enter');
  // await page1.getByRole('button', { name: 'Login' }).click();
  // await page1.getByText('Remind me later').click();
  // await page1.locator('#NavBarLink').getByText('Academics').click();
  // await page1.getByRole('link', { name: 'Career Profiling' }).click();
  // await page1.getByRole('heading', { name: 'Extra-Curricular Skills' }).click();
  // await page1.getByRole('heading', { name: 'Extra-Curricular Skills' }).click();
  // await page1.getByRole('heading', { name: 'Co-Curricular Skills' }).click();
  // await page1.getByText('Remind me later').click();
  // await expect(page1.locator('#KMyClass')).toContainText('My Class');
});